### ISSUE TITLE
The Great Ace Attorney import script

### ISSUE THREAD

**Issue by micah686** [masagrator/NXGameScripts#1]
Would you be willing to create a script that reimports/packs the files that were exported with the ArcUnpack.py for The Great Ace Attorney?

**Comment by masagrator** [comment]
I have made a repacker before (puts file at the end of arc instead of replacing file), but targeted to .gmd files. I will share it here and you can do whatever you want with it. 

https://gist.github.com/masagrator/6935eddc92e739be4d1cddcb7b64f4ad

As first argument you're providing .arc file

it checks for .gmd files in `patched\*arc filename without any type*` (for example `patched\msg_cmn_eng`) folder (with all folder structures that leads to this file)
and puts new .arc file to `repacked` folder
