### ISSUE TITLE
Cross Channel Assemble and Dissemble

### ISSUE THREAD

**Issue by seahwm** [masagrator/NXGameScripts#8]
Hi, wanna ask, does these script applicable for C+C Final Complete PC edition? I saw the dissembler works well, but the assembler not works (I did not edit the json, just simply dissemble and assemble). It fails when detected "WITH_TXT" type, but can't find the "STRING" attribute

JSON:
![image](https://github.com/user-attachments/assets/c9ace383-422e-46ec-813a-fc7403e3e8e0)
 Err Log:
![image](https://github.com/user-attachments/assets/f3fc2657-f73b-4964-9667-d32c87e08283)

**Comment by masagrator** [comment]
It was not fully tested and it's abandoned. 

After comparing PC script for All Ages version vs Switch I have learned that Switch version is even more censored than OC version with altered lines that don't exist in PC version. And since English PC version doesn't have Japanese script, there is no easy way to replace texts via comparison.
English PC version uses different engine than Japanese PC version, so it's not possible to easily merge texts.

**Comment by masagrator** [comment]
Now I read you are asking for PC version.

I didn't update assembler to work with PC version. It was made for Switch with disassembler, then I was asked by someone I know if I can update disassembler for PC version. It was easy, because it has exactly the same opcode table as Switch version, just some opcodes and variables that weren't used on Switch are used on PC, so it works both for Switch and PC. 

I don't plan to update it unless someone I know will ask about that. And since that person is busy with other projects, that won't be them anytime soon.

**Comment by masagrator** [comment]
Or no, it seems I didn't update assembler at all to work with updated disassembler, so it won't even work with Switch version.

**Comment by masagrator** [comment]
Okay, fixed assembler and updated disassembler because one value was parsed in wrong way.

Now after assembling all files are the same from `sn` and `sn_new` folders for PC version. It should be the same for Switch.

original sn.bin and `Out/sn.bin` produced by sn_assembler.py will look different because python lzss library uses different settings than LZ01, but they are using the same rules for decompression, so it will work fine.

**Comment by masagrator** [comment]
Ah, also RenameTexts.py and RenameBackTexts.py list with filenames was filled by analyzing 0000.json manually. 

List is designed for Switch only, you must update list if you want properly named files instead of numbers

**Comment by seahwm** [comment]
Ok, thanks. Also wanna ask is it any reference of the opcode table u mentioned, so I can do it my own for PC version?

**Comment by masagrator** [comment]
Everything is in executable. I am not well versed in x86 executables , only AArch64. So I don't know how they are stored on PC.

On Switch executable stores opcode function pointers in one array, it's easy to find by using IDA and going through nullsubs, at some point by checking one by one you will see reference to that array, and this array will have the size matching opcode count + it will have multiple different nullsubs
